### PR TITLE
Added some ui/ux changes

### PR DESCRIPTION
**Pull request by ayush1009208**

### CODE REVIEW

**Comment by Shivg2901** [comment]
@ayush1009208 The code looks very promising ayush
please provide screenshots and i'll merge right away

**Comment by ayush1009208** [comment]
image
image

**Comment by Shivg2901** [comment]
@ayush1009208 
The ui looks good but what are those errors

**Comment by ayush1009208** [comment]
Its some error from backend

**Comment by Shivg2901** [comment]
Please elaborate or just send ss of the error

**Comment by ayush1009208** [comment]
It seems the app is not able to fetch details from database'

**Comment by ayush1009208** [comment]
image

**Comment by Shivg2901** [comment]
Thats alright
just one small thing remove the 
'//just a commit'

**Comment by ayush1009208** [comment]
Ohhk i am pushing again

**Comment by Shivg2901** [comment]
Great work @ayush1009208

**Comment by ayush1009208** [comment]
Thanks : )

**Pull request merged**
