### PR TITLE
Update page.tsx

### PR DESCRIPTION
**Pull request by Amansingh0807**
I optimized the useEffect hook with an empty dependency array to prevent repeated API calls and added error handling using .catch() in Axios to manage request failures. I also implemented a check for the authorization token in localStorage and dynamically rendered the Zap creation date using new Date().toLocaleDateString(). also i wrote it in issue #14

### CODE REVIEW

**Comment by Shivg2901** [comment]
@Amansingh0807 
Please provide screenshot for the date part
I suspect that it wont show the actual date it was created at but instead show current date

**Comment by Amansingh0807** [comment]
> @Amansingh0807 Please provide screenshot for the date part

Screenshot 2024-10-19 140818
  now getting error to the sign up,
As soon as I sign up, I will send you a screenshot.

**Comment by Amansingh0807** [comment]
> @Amansingh0807 Please provide screenshot for the date part

Untitled design (1)
as soon as i will sign up i will share screenshot of that as of now i am getting error

**Comment by Shivg2901** [comment]
@Amansingh0807 Did you not setup the database

**Comment by Amansingh0807** [comment]
> @Amansingh0807 Did you not setup the database Also how did you contribute if you were unable to set it up

i did set up all of that but the error was coming into my laptop i don't know why and now i am doing it from another PC so will be doing the same u said in just couple of hours

**Comment by Shivg2901** [comment]
@Amansingh0807 screenshot?
Else i'll have to close

**Pull request closed without merging**
