### PR TITLE
Changed the default "Nov 13" to current date 

### PR DESCRIPTION
**Pull request by Suvendu-UI**

### CODE REVIEW

**Comment by Suvendu-UI** [comment]
hey @Shivg2901 i had done 1 silly mistake just corrected it

**Comment by Suvendu-UI** [comment]
and yes i tried to run the repo but that was taking a hell lot of time to install kafka only

**Comment by Suvendu-UI** [comment]
hey @Shivg2901 running the repo took a lot of time but i was seeing much errors in the build 
so i just gave it to gpt to tell what would show in the browser it shows the day month and year
image

**Comment by Shivg2901** [comment]
I'll set it up and try it out in a couple of days
During that try to set it up
Even If you can't it's fine

**Comment by Shivg2901** [comment]
@Suvendu-UI I have to close this pr because it does'nt solve the issue 
This has to be solved at both fe and be 
This shows the current date and not the date the zap was created
Please refrain from picking up issues and putting on chat gpt

**Pull request closed without merging**
