### PR TITLE
Push

### PR DESCRIPTION
**Pull request by ayush1009208**

### CODE REVIEW

**Comment by ayush1009208** [comment]
Hey check this now...

**Comment by Shivg2901** [comment]
@ayush1009208 
Bro you messed up the repo a little bit
You created a new frontend named app for some reason
now you have done changes in two different places

**Comment by Shivg2901** [comment]
@ayush1009208 
i have reverted your previous pr
combine the changes in the two
in the frontend folder only

**Comment by ayush1009208** [comment]
Sorry...@Shivg2901 I am sorry for this.I was in a bit hurry.So i pasted the issue in gpt directly.
If you want I can fix the issue at night

**Comment by Shivg2901** [comment]
@ayush1009208 
Its okay ayush dont worry
You may proceed

**Comment by ayush1009208** [comment]
@Shivg2901 I have a doubt will mt contribution count in hacktober?

**Comment by Shivg2901** [comment]
@ayush1009208 
Yes all the merged ones will count
The first contribution too

**Comment by ayush1009208** [comment]
Thanks

**Pull request closed without merging**
